version: '3.8'

services:
  appurihako:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appurihako
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
