services:
  appurihako:
    image: ghcr.io/ankit99925/appurihako:latest
    container_name: appurihako
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge